# Generated by Django 6.0 on 2025-12-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_conversation_created_by'),
    ]

    operations = [
    ]
