# Generated by Django 6.0 on 2026-01-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_status'),
        ('message', '0005_message_delivered_to_message_seen_by'),
    ]

    operations = [
    ]
