# Generated by Django 6.0 on 2025-12-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_headline_profile_location_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE profiles_profile SET headline = '' WHERE headline IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunSQL(
            "UPDATE profiles_profile SET location = '' WHERE location IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunSQL(
            "UPDATE profiles_profile SET portfolio_url = '' WHERE portfolio_url IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='profile',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RunSQL(
            "UPDATE profiles_profile SET skills = '' WHERE skills IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated skills', max_length=512, null=True),
        ),
    ]
