# Generated by Django 6.0 on 2026-01-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPanel', '0002_job_application_deadline_job_experience_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (only filled when status is rejected)'),
        ),
    ]
